import {NavLink} from 'react-router-dom';
const menuInfo=[
    {
        title:"介绍",
        key:"introduce"
    },
    {
        title:"组件",
        key:"component",
        children:[
            {
                title:"tooltip",
                key:"tooltip",
            },
            {
                title:"popper",
                key:"popper",
            },
            {
                title:"Loading",
                key:"loading",
            },
            {
                title:"回到顶部",
                key:"backtop",
            },
            {
                title:"Divider",
                key:"divider",
            },
            {
                title:"Space",
                key:"space",
            },
            {
                title:"Typography",
                key:"typography",
            },
            {
                title:"Layout布局",
                key:"layout",
            },
            {
                title:"Switch",
                key:"switch",
            },
            {
                title:"Radio",
                key:"radio",
            },
            {
                title:"animation",
                key:"animation",
            },
            {
                title:"Pager",
                key:"pager",
            },
            {
                title:"Input",
                key:"input",
            },
            {
                title:"Notification",
                key:"notification",
            },
            {
                title:"Grid",
                key:"grid",
                
            },
            {
                title:"按钮",
                key:"button",
                
            },
            {
                title:"Icon",
                key:"icon",
            },
            {
                title:"电池动画",
                key:"battery-animation-demo",
            },
            {
                title:"上传demo",
                key:"upload",
            },
            
        ]
    }
];

export {
    menuInfo
}